spring:
  application:
    name: heythere-mail-server
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: com.heythere@gmail.com
    password: 1q2w3e**
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
